import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.6.1"

    const val navigation_safe_args_gradle_plugin: String = "2.2.0-alpha03"

    const val com_android_tools_build_gradle: String = "3.5.0"

    const val kotlinx_serialization_runtime: String = "0.13.0"

    const val kotlinx_coroutines_android: String = "1.3.2"

    const val org_permissionsdispatcher: String = "4.5.0"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val kotlinx_coroutines_core: String = "1.3.2"

    const val navigation_fragment_ktx: String = "2.1.0"

    const val androidx_databinding: String = "3.5.0"

    const val org_jetbrains_kotlin: String = "1.3.50"

    const val androidx_concurrent: String = "1.0.0-beta01"

    const val androidx_lifecycle: String = "2.1.0"

    const val navigation_ui_ktx: String = "2.1.0"

    const val constraintlayout: String = "1.1.3"

    const val androidx_paging: String = "2.1.0"

    const val androidx_room: String = "2.2.0-alpha01"

    const val androidx_work: String = "2.2.0"

    const val espresso_core: String = "3.2.0"

    const val core_testing: String = "2.1.0"

    const val junit_junit: String = "4.12"

    const val lint_gradle: String = "26.5.0"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.1.0"

    const val aapt2: String = "3.5.0-5435860"

    /**
     * Current version: "5.6.2"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6.2"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
