/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidmediapractice_main_task2_LameWrapper */

#ifndef _Included_com_example_androidmediapractice_main_task2_LameWrapper
#define _Included_com_example_androidmediapractice_main_task2_LameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    init
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_init
    (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_encode
    (JNIEnv *, jobject);

/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_destroy
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
