/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_androidmediapractice_main_task2_LameWrapper */

#ifndef _Included_com_example_androidmediapractice_main_task2_LameWrapper
#define _Included_com_example_androidmediapractice_main_task2_LameWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_init
    (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    encode
 * Signature: ([S[SI[B)V
 */
JNIEXPORT void JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_encode
    (JNIEnv *, jobject, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_flush
    (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_androidmediapractice_main_task2_LameWrapper
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_androidmediapractice_main_task2_LameWrapper_close
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
